export const QC_BARANGAYS = [
  'Alicia','Amihan','Apolonio Samson','Aurora','Bagbag','Bagong Bayan',
  'Bagong Pag-asa','Bagong Silangan','Bagong Silang','Bagumbayan',
  'Bagumbuhay','Bahay Toro','Balingasa','Batasan Hills','Batis',
  'Blue Ridge A','Blue Ridge B','Botocan','Camp Aguinaldo','Capri',
  'Central','Commonwealth','Culiat','Damar','Damayan','Damayan Lagi',
  'Del Monte','Dioquino Zobel','Don Manuel','Dona Aurora','Dona Imelda',
  'Dona Josefa','Escopa I','Escopa II','Escopa III','Escopa IV',
  'Fairview','Filinvest II','G.S.I.S.','Gulod','Holy Spirit',
  'Horseshoe','Immaculate Concepcion','Kaligayahan','Kalusugan',
  'Kamuning','Katipunan','Kaunlaran','Kristong Hari','Krus na Ligas',
  'Laging Handa','Libis','Lourdes','Loyola Heights','Lucban',
  'Luzon','Maharlika','Malaya','Mangga','Manresa','Mariana',
  'Mariblo','Marilag','Masagana','Masambong','Matandang Balara',
  'Milagrosa','Nagkaisang Nayon','Nayon ng Bulaklak','New Era',
  'New Fairview','Novaliches Proper','Obrero','Old Capitol Site',
  'Paang Bundok','Pag-ibig sa Nayon','Pansol','Paraiso',
  'Pasong Putik Proper','Pasong Tamo','Payatas','Phil-Am','Pinagkaisahan',
  'Project 4','Project 6','Project 7','Project 8',
  'Provident Village','Quirino 2-A','Quirino 2-B','Quirino 2-C',
  'Quirino 3-A','Ramon Magsaysay','Sacred Heart','Saint Ignatius',
  'Saint Peter','Salvacion','San Agustin','San Antonio',
  'San Bartolome','San Isidro','San Isidro Labrador','San Jose',
  'San Roque','Sangandaan','Santa Cruz','Santa Lucia','Santa Monica',
  'Santo Cristo','Santo Domingo','Santo Nino','Santol','Sauyo',
  'Siena','Sikatuna Village','Socorro','South Triangle','Tagumpay',
  'Talayan','Tandang Sora','Tatalon','Teachers Village East',
  'Teachers Village West','Ugong Norte','U.P. Campus','U.P. Village',
  'Vasra','Veterans Village','Villa Maria Clara','West Triangle','White Plains'
]

export const CATEGORIES = [
  { id: 'flood',   label: 'Flood',        color: '#1D4ED8', bg: '#DBEAFE' },
  { id: 'medical', label: 'Medical',      color: '#9D174D', bg: '#FCE7F3' },
  { id: 'traffic', label: 'Traffic',      color: '#92400E', bg: '#FEF3C7' },
  { id: 'fire',    label: 'Fire',         color: '#991B1B', bg: '#FEE2E2' },
  { id: 'lost',    label: 'Lost & Found', color: '#5B21B6', bg: '#EDE9FE' },
  { id: 'crime',   label: 'Crime',        color: '#9F1239', bg: '#FFE4E6' },
  { id: 'info',    label: 'Info',         color: '#065F46', bg: '#ECFDF5' },
  { id: 'other',   label: 'Other',        color: '#475569', bg: '#F1F5F9' },
]

export const SAMPLE_POSTS = [
  {
    id: 'post_001',
    authorId: 'uid_maria',
    author: 'Maria Santos',
    avatar: 'MS',
    avatarColor: '#FCE7F3',
    avatarText: '#9D174D',
    barangay: 'Batasan Hills',
    time: '5m ago',
    category: 'flood',
    tags: ['flood', 'urgent'],
    text: 'Floodwater rising rapidly along Batasan Road near the creek. Several families stranded — need immediate evacuation. Water already at knee height near the bridge. QCDRRMO has been notified.',
    likes: 24,
    comments: 8,
    status: 'open',
    priority: 'urgent',
    timestamp: Date.now() - 300000,
    location: 'Batasan Road cor. Creek Road',
  },
  {
    id: 'post_002',
    authorId: 'uid_jose',
    author: 'Jose Reyes',
    avatar: 'JR',
    avatarColor: '#ECFDF5',
    avatarText: '#065F46',
    barangay: 'Commonwealth',
    time: '18m ago',
    category: 'medical',
    tags: ['medical'],
    text: 'Urgently looking for O+ blood donor for an emergency operation at Quezon City General Hospital (QCGH). Patient is a 62-year-old male. Please contact the hospital directly at 8988-8000 ext 302.',
    likes: 41,
    comments: 15,
    status: 'open',
    priority: 'urgent',
    timestamp: Date.now() - 1080000,
    location: 'QC General Hospital, Seminary Road',
  },
  {
    id: 'post_003',
    authorId: 'uid_ana',
    author: 'Ana Villanueva',
    avatar: 'AV',
    avatarColor: '#EDE9FE',
    avatarText: '#5B21B6',
    barangay: 'Fairview',
    time: '1h ago',
    category: 'lost',
    tags: ['lost'],
    text: 'FOUND: Brown Labrador named "Kiko", red collar. Last seen near Fairview Terraces yesterday. Now safe with me in Kaligayahan. Owner please call 09171234567. Thank you to all who helped search!',
    likes: 67,
    comments: 22,
    status: 'resolved',
    priority: 'normal',
    timestamp: Date.now() - 3600000,
    location: 'Kaligayahan, near Fairview Terraces',
  },
  {
    id: 'post_004',
    authorId: 'uid_carlos',
    author: 'Carlos Mendoza',
    avatar: 'CM',
    avatarColor: '#FFF7ED',
    avatarText: '#9A3412',
    barangay: 'Cubao',
    time: '2h ago',
    category: 'traffic',
    tags: ['traffic', 'info'],
    text: 'Major road closure at EDSA-Cubao underpass — ongoing QC LGU rehabilitation works. Expect congestion until 6PM. Alternate route: Aurora Blvd to Araneta Ave. MMDA already on-site.',
    likes: 132,
    comments: 47,
    status: 'open',
    priority: 'normal',
    timestamp: Date.now() - 7200000,
    location: 'EDSA-Cubao Underpass, near Araneta Center',
  },
  {
    id: 'post_005',
    authorId: 'uid_noel',
    author: 'Noel Garcia',
    avatar: 'NG',
    avatarColor: '#FFF0F0',
    avatarText: '#9A0000',
    barangay: 'Holy Spirit',
    time: '3h ago',
    category: 'info',
    tags: ['info'],
    text: 'QC LGU Free Medical Mission at Barangay Holy Spirit Basketball Court tomorrow, 8AM–4PM. Services: general check-up, dental, eye care, blood pressure monitoring, and medicines. Bring valid QC ID or barangay clearance.',
    likes: 88,
    comments: 31,
    status: 'open',
    priority: 'normal',
    timestamp: Date.now() - 10800000,
    location: 'Holy Spirit Basketball Court, Holy Spirit Drive',
  },
  {
    id: 'post_006',
    authorId: 'uid_rosa',
    author: 'Rosa Bautista',
    avatar: 'RB',
    avatarColor: '#F0FDF4',
    avatarText: '#065F46',
    barangay: 'Pasong Tamo',
    time: '4h ago',
    category: 'flood',
    tags: ['flood'],
    text: 'Pasong Tamo Creek overflowing near Brgy Hall. Street level already flooded. Families near the riverbank advised to evacuate to Pasong Tamo Elementary School. Bring medicines and important documents.',
    likes: 55,
    comments: 19,
    status: 'in_progress',
    priority: 'urgent',
    timestamp: Date.now() - 14400000,
    location: 'Pasong Tamo Creek, near Barangay Hall',
  },
]

export const ANNOUNCEMENTS = [
  {
    id: 'ann_001',
    source: 'PAGASA-AGASA',
    icon: 'cloud-rain',
    title: 'Rainfall Advisory #2 — Quezon City',
    body: 'Moderate to heavy rains expected over Batasan Hills, Commonwealth, and Payatas areas. Low-lying barangays on flooding alert. Issued: March 28, 2026 10:00 AM',
    time: '2m ago',
    type: 'warning',
    link: 'https://www.pagasa.dost.gov.ph',
  },
  {
    id: 'ann_002',
    source: 'QC LGU – Iskolar ng QC',
    icon: 'graduation',
    title: 'Iskolar ng QC Scholarship – Application Open',
    body: 'Apply at your Barangay Hall until April 30, 2026. Requirements: QC ID, School Enrollment Form, Family Income Certificate. For SY 2026–2027.',
    time: '1h ago',
    type: 'info',
    link: 'https://quezoncity.gov.ph',
  },
  {
    id: 'ann_003',
    source: 'QC Health Department',
    icon: 'health',
    title: 'Free Medical Mission – Novaliches Proper',
    body: 'QC Free Medical Mission at Novaliches Proper Plaza on April 5, 2026, 8AM–5PM. General check-up, dental, and eye care. Open to all QC residents.',
    time: '3h ago',
    type: 'health',
    link: 'https://quezoncity.gov.ph',
  },
]

export const MAP_MARKERS = [
  { id: 'm_001', type: 'emergency', lat: 14.685, lng: 121.072, title: 'Flooding – Batasan Road cor. Tandang Sora', detail: 'Reported 25 mins ago · 3 families need evacuation', postId: 'post_001' },
  { id: 'm_002', type: 'community', lat: 14.676, lng: 121.048, title: 'Volunteer Needed – Holy Spirit food distribution', detail: 'Reported 1h ago · 50 families to be served', postId: 'post_005' },
  { id: 'm_003', type: 'active', lat: 14.652, lng: 121.033, title: 'EDSA-Cubao road closure – rehabilitation works', detail: 'Reported 2h ago · MMDA on-site', postId: 'post_004' },
  { id: 'm_004', type: 'emergency', lat: 14.691, lng: 121.041, title: 'Blood donor needed – QC General Hospital', detail: 'Reported 18 mins ago · O+ blood type needed', postId: 'post_002' },
  { id: 'm_005', type: 'cluster', lat: 14.660, lng: 121.055, title: '4 Reports – Commonwealth Ave corridor', detail: 'Mix of flood, traffic, and info reports', postId: null },
  { id: 'm_006', type: 'active', lat: 14.637, lng: 121.022, title: 'Pasong Tamo Creek overflow – evacuation advisory', detail: 'Reported 4h ago · Families evacuated to school', postId: 'post_006' },
]

export const ADMIN_POSTS_TABLE = [
  { postId: 'post_001', userId: 'uid_maria', userName: 'Maria Santos', barangay: 'Batasan Hills', category: 'flood', status: 'open', timestamp: '2026-03-28 14:32', priority: 'urgent' },
  { postId: 'post_002', userId: 'uid_jose', userName: 'Jose Reyes', barangay: 'Commonwealth', category: 'medical', status: 'open', timestamp: '2026-03-28 14:19', priority: 'urgent' },
  { postId: 'post_003', userId: 'uid_ana', userName: 'Ana Villanueva', barangay: 'Fairview', category: 'lost', status: 'resolved', timestamp: '2026-03-28 13:37', priority: 'normal' },
  { postId: 'post_004', userId: 'uid_carlos', userName: 'Carlos Mendoza', barangay: 'Cubao', category: 'traffic', status: 'open', timestamp: '2026-03-28 12:37', priority: 'normal' },
  { postId: 'post_005', userId: 'uid_noel', userName: 'Noel Garcia', barangay: 'Holy Spirit', category: 'info', status: 'open', timestamp: '2026-03-28 11:37', priority: 'normal' },
  { postId: 'post_006', userId: 'uid_rosa', userName: 'Rosa Bautista', barangay: 'Pasong Tamo', category: 'flood', status: 'in_progress', timestamp: '2026-03-28 10:37', priority: 'urgent' },
  { postId: 'post_007', userId: 'uid_pedro', userName: 'Pedro Lim', barangay: 'Payatas', category: 'crime', status: 'open', timestamp: '2026-03-28 09:14', priority: 'normal' },
  { postId: 'post_008', userId: 'uid_dina', userName: 'Dina Cruz', barangay: 'Novaliches Proper', category: 'info', status: 'open', timestamp: '2026-03-28 08:02', priority: 'normal' },
]

export const ADMIN_USERS_TABLE = [
  { uid: 'uid_maria', name: 'Maria Santos', email: 'maria.santos@gmail.com', barangay: 'Batasan Hills', role: 'resident', verified: true, signInMethod: 'google', joinedAt: '2025-11-12' },
  { uid: 'uid_jose', name: 'Jose Reyes', email: 'jose.reyes@yahoo.com', barangay: 'Commonwealth', role: 'resident', verified: true, signInMethod: 'email', joinedAt: '2025-10-05' },
  { uid: 'uid_ana', name: 'Ana Villanueva', email: 'ana.v@gmail.com', barangay: 'Fairview', role: 'resident', verified: false, signInMethod: 'google', joinedAt: '2026-01-18' },
  { uid: 'uid_carlos', name: 'Carlos Mendoza', email: 'carlos.m@hotmail.com', barangay: 'Cubao', role: 'admin', verified: true, signInMethod: 'email', joinedAt: '2025-09-30' },
  { uid: 'uid_noel', name: 'Noel Garcia', email: 'noel.g@gmail.com', barangay: 'Holy Spirit', role: 'resident', verified: true, signInMethod: 'facebook', joinedAt: '2026-02-01' },
  { uid: 'uid_rosa', name: 'Rosa Bautista', email: 'rosa.bautista@gmail.com', barangay: 'Pasong Tamo', role: 'resident', verified: false, signInMethod: 'email', joinedAt: '2026-03-10' },
  { uid: 'uid_pedro', name: 'Pedro Lim', email: 'pedro.lim@qc.gov.ph', barangay: 'Payatas', role: 'admin', verified: true, signInMethod: 'google', joinedAt: '2025-08-22' },
  { uid: 'uid_dina', name: 'Dina Cruz', email: 'dina.c@gmail.com', barangay: 'Novaliches Proper', role: 'resident', verified: true, signInMethod: 'google', joinedAt: '2026-01-07' },
]

export const BARANGAY_STATS = [
  { name: 'Batasan Hills', posts: 247, resolved: 189, coverage: 82 },
  { name: 'Commonwealth', posts: 198, resolved: 142, coverage: 74 },
  { name: 'Fairview', posts: 176, resolved: 104, coverage: 65 },
  { name: 'Novaliches Proper', posts: 154, resolved: 87, coverage: 58 },
  { name: 'Cubao', posts: 312, resolved: 289, coverage: 91 },
  { name: 'Holy Spirit', posts: 128, resolved: 59, coverage: 47 },
  { name: 'Payatas', posts: 143, resolved: 76, coverage: 53 },
  { name: 'Pasong Tamo', posts: 89, resolved: 61, coverage: 68 },
]
