export const QC_BARANGAYS = [
  'Alicia','Amihan','Apolonio Samson','Aurora','Bagbag','Bagong Bayan',
  'Bagong Pag-asa','Bagong Silangan','Bagong Silang','Bagumbayan',
  'Bagumbuhay','Bahay Toro','Balingasa','Batasan Hills','Batis',
  'Blue Ridge A','Blue Ridge B','Botocan','Camp Aguinaldo','Capri',
  'Central','Commonwealth','Culiat','Damar','Damayan','Damayan Lagi',
  'Del Monte','Dioquino Zobel','Don Manuel','Dona Aurora','Dona Imelda',
  'Dona Josefa','Escopa I','Escopa II','Escopa III','Escopa IV',
  'Fairview','Filinvest II','G.S.I.S.','Gulod','Holy Spirit',
  'Horseshoe','Immaculate Concepcion','Kaligayahan','Kalusugan',
  'Kamuning','Katipunan','Kaunlaran','Kristong Hari','Krus na Ligas',
  'Laging Handa','Libis','Lourdes','Loyola Heights','Lucban',
  'Luzon','Maharlika','Malaya','Mangga','Manresa','Mariana',
  'Mariblo','Marilag','Masagana','Masambong','Matandang Balara',
  'Milagrosa','Nagkaisang Nayon','Nayon ng Bulaklak','New Era',
  'New Fairview','Novaliches','Obrero','Old Capitol Site',
  'Paang Bundok','Pag-ibig sa Nayon','Pansol','Paraiso',
  'Pasong Putik','Payatas','Phil-Am','Pinagkaisahan',
  'Project 4','Project 6','Project 7','Project 8',
  'Provident Village','Quirino 2-A','Quirino 2-B','Quirino 2-C',
  'Quirino 3-A','Ramon Magsaysay','Sacred Heart','Saint Ignatius',
  'Saint Peter','Salvacion','San Agustin','San Antonio',
  'San Bartolome','San Isidro','San Isidro Labrador','San Jose',
  'San Roque','Sangandaan','Santa Cruz','Santa Lucia','Santa Monica',
  'Santo Cristo','Santo Domingo','Santo Nino','Santol','Sauyo',
  'Siena','Sikatuna Village','Socorro','South Triangle','Tagumpay',
  'Talayan','Tandang Sora','Tatalon','Teachers Village East',
  'Teachers Village West','Ugong Norte','U.P. Campus','U.P. Village',
  'Vasra','Veterans Village','Villa Maria Clara','West Triangle','White Plains'
]

export const CATEGORIES = [
  { id: 'flood',   label: 'Flood',       icon: 'CloudRain'     },
  { id: 'medical', label: 'Medical',     icon: 'HeartPulse'    },
  { id: 'traffic', label: 'Traffic',     icon: 'Car'           },
  { id: 'fire',    label: 'Fire',        icon: 'Flame'         },
  { id: 'lost',    label: 'Lost & Found',icon: 'Search'        },
  { id: 'crime',   label: 'Crime',       icon: 'ShieldAlert'   },
  { id: 'info',    label: 'Info',        icon: 'Info'          },
  { id: 'other',   label: 'Other',       icon: 'MoreHorizontal'},
]

export const SAMPLE_POSTS = [
  {
    id: '1',
    author: 'Maria Santos',
    avatar: 'MS',
    avatarColor: '#FCE7F3',
    avatarText: '#9D174D',
    barangay: 'Batasan Hills',
    time: '5m ago',
    category: 'flood',
    tags: ['flood','urgent'],
    text: 'Floodwater is rising rapidly along Batasan Road. Several families need immediate evacuation assistance. Water level is at knee height already.',
    likes: 24,
    comments: 8,
    status: 'open',
    timestamp: Date.now() - 300000,
  },
  {
    id: '2',
    author: 'Jose Reyes',
    avatar: 'JR',
    avatarColor: '#ECFDF5',
    avatarText: '#065F46',
    barangay: 'Commonwealth',
    time: '18m ago',
    category: 'medical',
    tags: ['medical'],
    text: 'Looking for a voluntary blood donor with blood type O+ for an emergency operation at Quezon City General Hospital. Please contact immediately.',
    likes: 41,
    comments: 15,
    status: 'open',
    timestamp: Date.now() - 1080000,
  },
  {
    id: '3',
    author: 'Ana Villanueva',
    avatar: 'AV',
    avatarColor: '#EDE9FE',
    avatarText: '#5B21B6',
    barangay: 'Fairview',
    time: '1h ago',
    category: 'lost',
    tags: ['lost'],
    text: 'Lost: Brown Labrador named "Kiko", wearing a red collar. Last seen near Fairview Park yesterday afternoon. Please call if found.',
    likes: 67,
    comments: 22,
    status: 'resolved',
    timestamp: Date.now() - 3600000,
  },
  {
    id: '4',
    author: 'Carlos Mendoza',
    avatar: 'CM',
    avatarColor: '#FFF7ED',
    avatarText: '#9A3412',
    barangay: 'Cubao',
    time: '2h ago',
    category: 'traffic',
    tags: ['traffic','info'],
    text: 'Major road closure at EDSA-Cubao underpass due to ongoing rehabilitation works. Expect heavy traffic until 6PM. Suggest using alternate routes via Aurora Blvd.',
    likes: 132,
    comments: 47,
    status: 'info',
    timestamp: Date.now() - 7200000,
  },
]
