export const QC_BARANGAYS = [
  'Alicia','Amihan','Apolonio Samson','Aurora','Bagbag','Bagong Bayan',
  'Bagong Pag-asa','Bagong Silangan','Bagong Silang','Bagumbayan',
  'Bagumbuhay','Bahay Toro','Balingasa','Batasan Hills','Batis',
  'Blue Ridge A','Blue Ridge B','Botocan','Camp Aguinaldo','Capri',
  'Central','Commonwealth','Culiat','Damar','Damayan','Damayan Lagi',
  'Del Monte','Dioquino Zobel','Don Manuel','Dona Aurora','Dona Imelda',
  'Dona Josefa','Escopa I','Escopa II','Escopa III','Escopa IV',
  'Fairview','Filinvest II','G.S.I.S.','Gulod','Holy Spirit',
  'Horseshoe','Immaculate Concepcion','Kaligayahan','Kalusugan',
  'Kamuning','Katipunan','Kaunlaran','Kristong Hari','Krus na Ligas',
  'Laging Handa','Libis','Lourdes','Loyola Heights','Lucban',
  'Luzon','Maharlika','Malaya','Mangga','Manresa','Mariana',
  'Mariblo','Marilag','Masagana','Masambong','Matandang Balara',
  'Milagrosa','Nagkaisang Nayon','Nayon ng Bulaklak','New Era',
  'New Fairview','Novaliches Proper','Obrero','Old Capitol Site',
  'Paang Bundok','Pag-ibig sa Nayon','Pansol','Paraiso',
  'Pasong Putik Proper','Pasong Tamo','Payatas','Phil-Am','Pinagkaisahan',
  'Project 4','Project 6','Project 7','Project 8',
  'Provident Village','Quirino 2-A','Quirino 2-B','Quirino 2-C',
  'Quirino 3-A','Ramon Magsaysay','Sacred Heart','Saint Ignatius',
  'Saint Peter','Salvacion','San Agustin','San Antonio',
  'San Bartolome','San Isidro','San Isidro Labrador','San Jose',
  'San Roque','Sangandaan','Santa Cruz','Santa Lucia','Santa Monica',
  'Santo Cristo','Santo Domingo','Santo Nino','Santol','Sauyo',
  'Siena','Sikatuna Village','Socorro','South Triangle','Tagumpay',
  'Talayan','Tandang Sora','Tatalon','Teachers Village East',
  'Teachers Village West','Ugong Norte','U.P. Campus','U.P. Village',
  'Vasra','Veterans Village','Villa Maria Clara','West Triangle','White Plains'
]

export const CATEGORIES = [
  { id: 'flood',   label: 'Flood',        color: '#1D4ED8', bg: '#DBEAFE' },
  { id: 'medical', label: 'Medical',      color: '#9D174D', bg: '#FCE7F3' },
  { id: 'traffic', label: 'Traffic',      color: '#92400E', bg: '#FEF3C7' },
  { id: 'fire',    label: 'Fire',         color: '#991B1B', bg: '#FEE2E2' },
  { id: 'lost',    label: 'Lost & Found', color: '#5B21B6', bg: '#EDE9FE' },
  { id: 'crime',   label: 'Crime',        color: '#9F1239', bg: '#FFE4E6' },
  { id: 'info',    label: 'Info',         color: '#065F46', bg: '#ECFDF5' },
  { id: 'other',   label: 'Other',        color: '#475569', bg: '#F1F5F9' },
]
